[package]
name = "wasm-share-memory"
version = "0.1.0"
edition = "2024"

[lib]
name = "wasm_share_memory"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
walrus = "0.23.3"
wasm-bindgen = "0.2.100"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
