[package]
name = "wasm-multi-loader"
version = "0.1.0"
edition = "2024"

[lib]
name = "wasm_multi_loader"
path = "src/lib.rs"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
walrus = "0.23.3"
wasm-bindgen = "0.2.100"
