[workspace]
resolver = "3"

members = [
    "rust-cli",
    "rust-lib",
    "example/rust-library-common",
    "example/rust-library-A",
    "example/rust-library-B",
]

[profile.release]
opt-level = "s"
panic = "abort"
